### ISSUE TITLE
not work in sublime 2?

### ISSUE THREAD

**Issue by lymanlai** [samsonw/SublimeTask#4]
seems it is not work  at sublime 2. as it release before sublime 2 ;)

while I type the shortcut, nothing work?

I also define it in the user keymap file:
{ "keys": ["ctrl+shift+enter"], "command": "task"},

but while type it, nothing work .

Thanks

**Comment by samsonw** [comment]
Sorry for the delay guys, just fixed.  You will able to upgrade it through "Package Control" directly.  Let me know if you guys have issues.
