### ISSUE TITLE
About adding "In Progress" task

### ISSUE THREAD

**Issue by gmateo** [samsonw/SublimeTask#6]
Could you add a mark to point that a task is in progress state; something like this:
![gtdinprogress](https://cloud.githubusercontent.com/assets/819688/8319833/0e9b65c6-19d9-11e5-8daf-59ac24799831.png)

**Comment by samsonw** [comment]
Sounds interesting, I will take a look.  Thanks!

**Comment by gmateo** [comment]
For SublimeText 2, I made the following changes:


    def process(self, line):
        # below regex looks nice (works in ruby), but it won't work in python:
        # p = re.compile('^(\s*)([-✓])(.*)')
        # http://docs.python.org/howto/unicode
        p = re.compile(ur'^(\s*)(-|~|\xe2\x9c\x93)(.*)', re.UNICODE)
        m = p.match(line.encode(self.current_encoding()))
        if m:
            symbol = '-' 
            if m.group(2) == '-': 
               symbol = '~' 
            elif m.group(2) == '~': 
               symbol = '✓'

            #symbol = '✓' if m.group(2) == '-' else '-'
            result = '%(leading_whitespace)s%(symbol)s%(content)s' % {'leading_whitespace': m.group(1), 'symbol': symbol, 'content': m.group(3)}
            return result.decode(self.current_encoding())
        else:
            return None

    def current_encoding(self):
        if self.view.encoding() == 'Undefined':
            return self.view.settings().get('default_encoding', 'UTF-8')
        else:
            return self.view.encoding()

**Comment by samsonw** [comment]
Could you please submit a pull request, so we can see the diff more clearly and I'm glad to merge it if it's proved to be working!  Thanks!

**Comment by gmateo** [comment]
I will do that
